services:
  app_proxy:
    environment:
      APP_HOST: kriakiku-phantombot_server_1
      APP_PORT: 25000

  server:
    image: ghcr.io/phantombot/phantombot
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/opt/PhantomBot_data
    extra_hosts:
      - umbrel.local:127.0.0.1
    environment:
      PHANTOMBOT_ENVOVERRIDE: true
      PHANTOMBOT_USEHTTPS: false
      PHANTOMBOT_PROXYBYPASSHTTPS: true
      PHANTOMBOT_DEBUGON: false
      PHANTOMBOT_PANELUSER: umbrel
      PHANTOMBOT_PANELPASSWORD: $APP_PASSWORD
