services:
  server:
    image: ghcr.io/phantombot/phantombot:3.14.2.0@sha256:aff36a350eb3cb16799fa8ac4b668a596cd785c62b3bad4139c1b68f0ebbe7b3
    user: 0:900
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/opt/PhantomBot_data
      - ${APP_DATA_DIR}/public:/opt/PhantomBot/web/custom
    ports:
      - "${APP_PHANTOM_SERVER_PORT}:${APP_PHANTOM_SERVER_PORT}"
    environment:
      PHANTOMBOT_USEHTTPS: "true"
      PHANTOMBOT_PANELUSER: umbrel
      PHANTOMBOT_PANELPASSWORD: $APP_PASSWORD
      PHANTOMBOT_BASEPORT: $APP_PHANTOM_SERVER_PORT
