services:
  app_proxy:
    environment:
      APP_HOST: kriakiku-phantombot_server_1
      APP_PORT: 25000

  server:
    image: ghcr.io/phantombot/phantombot
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/opt/PhantomBot_data
      - ${APP_DATA_DIR}/cets:/umbrel_certs
      - ./entrypoint.sh:/umbrel_entrypoint.sh
    entrypoint: /umbrel_entrypoint.sh
    environment:
      PHANTOMBOT_ENVOVERRIDE: true
      
      PHANTOMBOT_USEHTTPS: true
      PHANTOMBOT_HTTPSFILENAME: /umbrel_certs/umbrel.local.crt
      PHANTOMBOT_HTTPSKEYFILENAME: /umbrel_certs/umbrel.local.key
      
      PHANTOMBOT_PANELUSER: umbrel
      PHANTOMBOT_PANELPASSWORD: $APP_PASSWORD
